Section "InputClass"
    Identifier "IBM Space Saver TrackPoint middle button scroll"
    MatchProduct "Composite USB PS2 Converter USB to PS2 Adaptor"
    MatchIsPointer "on"
    Driver "libinput"
    Option "ScrollMethod" "button"
    Option "ScrollButton" "2"
    Option "ScrollButtonLock" "false"
EndSection
